- name: Gathering Arista facts
  eos_facts:
  register: all_facts

- name: Get Existing Servers
  eos_command:
    commands:
      - "show run | i ntp server"
      - "show run | i aaa"
      - "show run | i logging host"
      - "show run | i snmp-server host"
  register: current_servers

- name: Create list of current servers
  set_fact:
    existing_ntp: "{{ current_servers.stdout[0] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
    existing_syslog: "{{ current_servers.stdout[1] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
    existing_aaa: "{{ current_servers.stdout[2] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
    existing_snmp: "{{ current_servers.stdout[3] | regex_findall('\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b') }}"
    desired_version: "{{ eos_version }}"
